version: "3"

services:
  nickelsh1ts:
    container_name: nickelsh1ts-dev
    build:
      context: .
      dockerfile: Dockerfile.local
    image: nickelsh1ts-dev:latest
    volumes:
      - .:/app:rw,cached
      - /app/node_modules
      - /app/.next
    restart: always
    ports:
      - 3024:3024
