version: "3"

services:
  nickelsh1ts:
    container_name: nickelsh1ts
    build:
      context: .
      dockerfile: Dockerfile
    image: nickelsh1ts:latest
    restart: always
    ports:
      - 3000:3000
