version: "3"

services:
  nickelsh1ts:
    container_name: nickelsh1ts
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:rw,cached
      - /app/node_modules
      - /app/.next
    restart: always
    ports:
      - 3024:3024
